-- MySQL Script generated by MySQL Workbench
-- Tue Oct 18 14:04:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `cod acesso` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `status` TINYINT(1) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod acesso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(100) NULL,
  `endereco` VARCHAR(100) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `codigovenda` INT NOT NULL,
  `valor` INT NOT NULL,
  `data` DATE NOT NULL,
  `atendente` INT NOT NULL,
  `funcionario_cod acesso` INT NOT NULL,
  `cliente_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`codigovenda`),
  INDEX `fk_venda_funcionario_idx` (`funcionario_cod acesso` ASC) VISIBLE,
  INDEX `fk_venda_cliente1_idx` (`cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_venda_funcionario`
    FOREIGN KEY (`funcionario_cod acesso`)
    REFERENCES `mydb`.`funcionario` (`cod acesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `mydb`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `valor` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `venda_codigovenda` INT NOT NULL,
  INDEX `fk_pagamento_venda1_idx` (`venda_codigovenda` ASC) VISIBLE,
  PRIMARY KEY (`venda_codigovenda`),
  CONSTRAINT `fk_pagamento_venda1`
    FOREIGN KEY (`venda_codigovenda`)
    REFERENCES `mydb`.`venda` (`codigovenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `numproduto` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `valor` INT NOT NULL,
  `estoque` INT NULL,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`numproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `produto_numproduto` INT NOT NULL,
  `venda_codigovenda` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  `desconto` FLOAT NULL,
  PRIMARY KEY (`produto_numproduto`, `venda_codigovenda`),
  INDEX `fk_produto_has_venda_venda1_idx` (`venda_codigovenda` ASC) VISIBLE,
  INDEX `fk_produto_has_venda_produto1_idx` (`produto_numproduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_venda_produto1`
    FOREIGN KEY (`produto_numproduto`)
    REFERENCES `mydb`.`produto` (`numproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_venda_venda1`
    FOREIGN KEY (`venda_codigovenda`)
    REFERENCES `mydb`.`venda` (`codigovenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `cnpj` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(100) NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lote` (
  `numerocompra` INT NOT NULL,
  `valor` INT NOT NULL,
  `data` DATE NOT NULL,
  `cnpj` INT NOT NULL,
  `funcionario_cod acesso` INT NOT NULL,
  `fornecedor_cnpj` INT NOT NULL,
  PRIMARY KEY (`numerocompra`),
  INDEX `fk_lote_funcionario1_idx` (`funcionario_cod acesso` ASC) VISIBLE,
  INDEX `fk_lote_fornecedor1_idx` (`fornecedor_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_lote_funcionario1`
    FOREIGN KEY (`funcionario_cod acesso`)
    REFERENCES `mydb`.`funcionario` (`cod acesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lote_fornecedor1`
    FOREIGN KEY (`fornecedor_cnpj`)
    REFERENCES `mydb`.`fornecedor` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pertence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pertence` (
  `lote_numerocompra` INT NOT NULL,
  `produto_numproduto` INT NOT NULL,
  PRIMARY KEY (`lote_numerocompra`, `produto_numproduto`),
  INDEX `fk_lote_has_produto_produto1_idx` (`produto_numproduto` ASC) VISIBLE,
  INDEX `fk_lote_has_produto_lote1_idx` (`lote_numerocompra` ASC) VISIBLE,
  CONSTRAINT `fk_lote_has_produto_lote1`
    FOREIGN KEY (`lote_numerocompra`)
    REFERENCES `mydb`.`lote` (`numerocompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lote_has_produto_produto1`
    FOREIGN KEY (`produto_numproduto`)
    REFERENCES `mydb`.`produto` (`numproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`promoção`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`promoção` (
  `produto_numproduto` INT NOT NULL,
  `funcionario_cod acesso` INT NOT NULL,
  `data` DATE NOT NULL,
  `desconto` FLOAT NULL,
  PRIMARY KEY (`produto_numproduto`, `funcionario_cod acesso`),
  INDEX `fk_produto_has_funcionario_funcionario1_idx` (`funcionario_cod acesso` ASC) VISIBLE,
  INDEX `fk_produto_has_funcionario_produto1_idx` (`produto_numproduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_funcionario_produto1`
    FOREIGN KEY (`produto_numproduto`)
    REFERENCES `mydb`.`produto` (`numproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_funcionario_funcionario1`
    FOREIGN KEY (`funcionario_cod acesso`)
    REFERENCES `mydb`.`funcionario` (`cod acesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`altera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`altera` (
  `item_produto_numproduto` INT NOT NULL,
  `item_venda_codigovenda` INT NOT NULL,
  `funcionario_cod acesso` INT NOT NULL,
  `data` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`item_produto_numproduto`, `item_venda_codigovenda`, `funcionario_cod acesso`),
  INDEX `fk_item_has_funcionario_funcionario1_idx` (`funcionario_cod acesso` ASC) VISIBLE,
  INDEX `fk_item_has_funcionario_item1_idx` (`item_produto_numproduto` ASC, `item_venda_codigovenda` ASC) VISIBLE,
  CONSTRAINT `fk_item_has_funcionario_item1`
    FOREIGN KEY (`item_produto_numproduto` , `item_venda_codigovenda`)
    REFERENCES `mydb`.`item` (`produto_numproduto` , `venda_codigovenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_funcionario_funcionario1`
    FOREIGN KEY (`funcionario_cod acesso`)
    REFERENCES `mydb`.`funcionario` (`cod acesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone_cliente` (
  `cliente_cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `tipo` VARCHAR(15) NOT NULL,
  INDEX `fk_telefone_cliente_cliente1_idx` (`cliente_cpf` ASC) VISIBLE,
  PRIMARY KEY (`cliente_cpf`, `telefone`),
  CONSTRAINT `fk_telefone_cliente_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `mydb`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone_fornecedor` (
  `fornecedor_cnpj` INT NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `tipo` VARCHAR(15) NOT NULL,
  INDEX `fk_telefone_fornecedor_fornecedor1_idx` (`fornecedor_cnpj` ASC) VISIBLE,
  PRIMARY KEY (`fornecedor_cnpj`, `telefone`),
  CONSTRAINT `fk_telefone_fornecedor_fornecedor1`
    FOREIGN KEY (`fornecedor_cnpj`)
    REFERENCES `mydb`.`fornecedor` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone_funcionario` (
  `funcionario_cod acesso` INT NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `tipo` VARCHAR(15) NOT NULL,
  INDEX `fk_telefone_funcionario_funcionario1_idx` (`funcionario_cod acesso` ASC) VISIBLE,
  PRIMARY KEY (`funcionario_cod acesso`, `telefone`),
  CONSTRAINT `fk_telefone_funcionario_funcionario1`
    FOREIGN KEY (`funcionario_cod acesso`)
    REFERENCES `mydb`.`funcionario` (`cod acesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
